/**
 * Utility functions for exporting the project and assets.
 */

export function generateMarkdownExport(project, assets) {
  let md = ''

  md += `# ${project.name}\n\n`
  md += `**Topic:** ${project.topic}\n`
  md += `**Niche:** ${project.niche}\n`
  md += `**Audience:** ${project.target_audience || 'General'}\n`
  md += `**Format:** ${project.script_format}\n`
  md += `**Length:** ${project.desired_length}\n\n`

  if (project.selected_title) {
    md += `## Selected Concept\n`
    md += `- **Title:** ${project.selected_title}\n`
    md += `- **Hook:** ${project.selected_hook}\n\n`
  }

  md += `---\n\n`

  // Helper to format JSON content into readable markdown
  const formatContent = (content) => {
    if (!content) return '*No content generated.*'
    
    // Attempt to stringify neatly based on structure
    let result = ''
    for (const [key, value] of Object.entries(content)) {
      // Convert camelCase to Title Case
      const formattedKey = key.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase())
      
      if (typeof value === 'string') {
        result += `### ${formattedKey}\n${value}\n\n`
      } else if (Array.isArray(value)) {
        result += `### ${formattedKey}\n`
        value.forEach(item => {
          if (typeof item === 'string') {
            result += `- ${item}\n`
          } else if (typeof item === 'object') {
            // For complex objects in arrays (like scenes, chapters)
            result += `- ${JSON.stringify(item)}\n` // Basic fallback for objects
          }
        })
        result += '\n'
      } else if (typeof value === 'object') {
        result += `### ${formattedKey}\n\`\`\`json\n${JSON.stringify(value, null, 2)}\n\`\`\`\n\n`
      }
    }
    return result
  }

  // 1. Research
  if (assets.research?.content) {
    md += `## 1. Topic Research\n\n`
    md += formatContent(assets.research.content)
    md += `---\n\n`
  }

  // 2. Strategy
  if (assets.strategy?.content) {
    md += `## 2. Video Strategy\n\n`
    md += formatContent(assets.strategy.content)
    md += `---\n\n`
  }

  // 3. Outline
  if (assets.outline?.content) {
    md += `## 3. Video Outline\n\n`
    md += formatContent(assets.outline.content)
    md += `---\n\n`
  }

  // 4. Script
  if (assets.script?.content) {
    md += `## 4. Full Script\n\n`
    md += formatContent(assets.script.content)
    md += `---\n\n`
  }
  
  // 5. Shorts
  if (assets.shorts?.content) {
    md += `## 5. Short-Form Variations\n\n`
    md += formatContent(assets.shorts.content)
    md += `---\n\n`
  }

  // 6. SEO
  if (assets.seo?.content) {
    md += `## 6. SEO Optimization\n\n`
    md += formatContent(assets.seo.content)
    md += `---\n\n`
  }

  // 7. Thumbnail
  if (assets.thumbnail?.content) {
    md += `## 7. Thumbnail Concepts\n\n`
    md += formatContent(assets.thumbnail.content)
    md += `---\n\n`
  }

  // 8. B-Roll
  if (assets.broll?.content) {
    md += `## 8. B-Roll Production Guide\n\n`
    md += formatContent(assets.broll.content)
    md += `---\n\n`
  }

  // 9. Voiceover
  if (assets.voiceover?.content) {
    md += `## 9. Voice-over Guide\n\n`
    md += formatContent(assets.voiceover.content)
    md += `---\n\n`
  }

  // 10. Summary
  if (assets.summary?.content) {
    md += `## 10. Production Summary\n\n`
    md += formatContent(assets.summary.content)
    md += `---\n\n`
  }

  md += `\n*Generated by StoryForge AI*\n`

  return md
}

export function downloadMarkdown(project, assets) {
  const mdContent = generateMarkdownExport(project, assets)
  const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8;' })
  const url = URL.createObjectURL(blob)
  
  const link = document.createElement('a')
  link.href = url
  link.download = `${project.name.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_content_package.md`
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}
